name: build and push docker image

on:
  push:
    branches: [main]
jobs:
  build_image:
    name: Build and push Image
    runs-on: ubuntu-22.04
    env: 
      REGION_NAME: eu-north-1
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
    permissions:
      id-token: write
      contents: read
      
    steps:  
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/githubactions-role
          role-session-name: GitHub
          aws-region: ${{ env.REGION_NAME }}

      - name: Login to Amazon ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region eu-north-1
          docker login -u AWS -p $(aws ecr get-login-password --region eu-north-1) ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-north-1.amazonaws.com
             
      - name: Get commit hash
        id: get-commit-hash
        run: echo "::set-output name=commit-hash::$(git rev-parse --short HEAD)"
      

      - name: Build image
        id: build-image
        env:
          ECR_REPOSITORY: my-repo
          ECR_REGISTRY: ${{ secrets.ACCOUNT_ID }}.dkr.ecr.${{ env.REGION_NAME }}.amazonaws.com/${{ env.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ steps.get-commit-hash.outputs.commit-hash }}  
        run: |
           docker build -t ${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} .
           docker tag  ${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-north-1.amazonaws.com/my-repo:01
           docker push  ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-north-1.amazonaws.com/my-repo:01

    
       
